# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Ville Petersson.'
tagline:          'Ville Petersson.'
description:      ''
url:              http://villep.se

author:
  name:           'Ville Petersson'
  url:            http://villep.se

paginate:         5
paginate_path:    'posts/page:num'


# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/villepetersson